name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag akerondocker/testrop:1.0.0
      - name: push image to docker hub
        run: |
          docker login -u akerondocker -p ${{ secrets.SECRET_TOKEN_HUB }}
          docker push akerondocker/testrop:1.0.0
      - name: log in to aws
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_default_region_name ${{ secrets.AWS_DEFAULT_REGION_NAME }}
          aws configure set aws_default_output_format "json"
      - name: Build the ecr
        run: |
          terraform init
          terraform apply -auto-approve -target module.ecr
